#include "SaveDataHelper.hpp"

#include <string>
#include "../../Adapter/OptionsAdapter.hpp"
#include "../../Adapter/HighScoresAdapter.hpp"
#include "../../Adapter/HighScoresModel.hpp"
#include "../../Game.hpp"
#include <memory.h>
#include <psputility.h>
#include <pspdisplay.h>
#include "../../Core/Config.hpp"

// Autogenerated with: `bin2c ICON0.PNG icon0.h icon0`
#include "icon0.h"

// Autogenerated with: `bin2c PIC1.PNG pic1.h pic1`
#include "pic1.h"

#define SAVE_NAME_OPTIONS "OPTIONS"
#define SAVE_NAME_HIGH_SCORES "SCORE"

void platformSaveOptions()
{
    SaveDataHelper::saveOptions();
}

void platformLoadOptions()
{
    SaveDataHelper::loadOptions();
}

void platformSaveHighScores()
{
    SaveDataHelper::saveHighScores();
}

void platformLoadHighScores()
{
    SaveDataHelper::loadHighScores();
}

namespace SaveDataHelper
{
    char key[] = SAVE_FILE_ENCRYPTION_KEY;

    void saveOptions()
    {
        OptionsModel options = OptionsAdapter::extractOptionsFromGame();
        std::string optionsXml = OptionsAdapter::serializeOptions(options);

        save(SAVE_NAME_OPTIONS, optionsXml, "Options");
    }

    void loadOptions()
    {
        std::string loadedData = load(SAVE_NAME_OPTIONS);

        OptionsModel options = OptionsAdapter::deserializeOptions(loadedData);
        OptionsAdapter::applyOptionsFromModel(options);
    }

    void saveHighScores()
    {
        HighScoresModel highScores = Game::highScores;
        std::string highScoresXml = HighScoresAdapter::serializeHighScores(highScores);

        save(SAVE_NAME_HIGH_SCORES, highScoresXml, "High Scores");
    }

    void loadHighScores()
    {
        std::string loadedData = load(SAVE_NAME_HIGH_SCORES);

        HighScoresModel highScores = HighScoresAdapter::deserializeHighScores(loadedData);
        Game::highScores = highScores;
    }

    void save(const std::string& saveName, const std::string& data, const std::string& title, const std::string& detail)
    {
        size_t dataSize = data.size() + 1;

        PspUtilitySavedataMode mode = PSP_UTILITY_SAVEDATA_AUTOSAVE;
        SceUtilitySavedataParam savedata;

        memset(&savedata, 0, sizeof(SceUtilitySavedataParam));
	    savedata.base.size = sizeof(SceUtilitySavedataParam);

        savedata.base.language = PSP_SYSTEMPARAM_LANGUAGE_ENGLISH;
        savedata.base.buttonSwap = PSP_UTILITY_ACCEPT_CROSS;
        savedata.base.graphicsThread = 0x11;
        savedata.base.accessThread = 0x13;
        savedata.base.fontThread = 0x12;
        savedata.base.soundThread = 0x10;

        savedata.mode = mode;
        savedata.overwrite = 1;

        #ifdef PLATFORM_PSP_SUPPORTS_SAVE_DATA_ENCRYPTION
            strncpy(savedata.key, key, 16);
        #endif

        strcpy(savedata.gameName, "DSREMIX");
        strcpy(savedata.saveName, saveName.c_str());

        strcpy(savedata.fileName, std::string(saveName + ".BIN").c_str());

        savedata.dataBuf = calloc(1, dataSize);
        savedata.dataBufSize = dataSize;
        savedata.dataSize = dataSize;
        strcpy((char*)savedata.dataBuf, data.c_str());
        
        strcpy(savedata.sfoParam.title, "Deadly Stages Remix");
        strcpy(savedata.sfoParam.savedataTitle, title.c_str());
        strcpy(savedata.sfoParam.detail, detail.c_str());

        savedata.pic1FileData.buf = pic1;
        savedata.pic1FileData.bufSize = size_pic1;
        savedata.pic1FileData.size = size_pic1;

        savedata.icon0FileData.buf = icon0;
        savedata.icon0FileData.bufSize = size_icon0;
        savedata.icon0FileData.size = size_icon0;

        sceUtilitySavedataInitStart(&savedata);

        bool saving = true;

        while (saving)
        {
            switch(sceUtilitySavedataGetStatus())
            {
            case PSP_UTILITY_DIALOG_INIT:
                break;

            case PSP_UTILITY_DIALOG_VISIBLE:
                sceUtilitySavedataUpdate(1);
                break;

            case PSP_UTILITY_DIALOG_QUIT:
                sceUtilitySavedataShutdownStart();
                break;

            case PSP_UTILITY_DIALOG_FINISHED:
                break;

            case PSP_UTILITY_DIALOG_NONE:
                saving = false;
                break;
            }

            sceDisplayWaitVblankStart();
        }
    }

    std::string load(const std::string& saveName)
    {
        PspUtilitySavedataMode mode = PSP_UTILITY_SAVEDATA_AUTOLOAD;
        SceUtilitySavedataParam savedata;

        memset(&savedata, 0, sizeof(SceUtilitySavedataParam));
	    savedata.base.size = sizeof(SceUtilitySavedataParam);

        savedata.base.language = PSP_SYSTEMPARAM_LANGUAGE_ENGLISH;
        savedata.base.buttonSwap = PSP_UTILITY_ACCEPT_CROSS;
        savedata.base.graphicsThread = 0x11;
        savedata.base.accessThread = 0x13;
        savedata.base.fontThread = 0x12;
        savedata.base.soundThread = 0x10;

        savedata.mode = mode;

        #ifdef PLATFORM_PSP_SUPPORTS_SAVE_DATA_ENCRYPTION
            strncpy(savedata.key, key, 16);
        #endif

        strcpy(savedata.gameName, "DSREMIX");
        strcpy(savedata.saveName, saveName.c_str());

        strcpy(savedata.fileName, std::string(saveName + ".BIN").c_str());

        size_t dataSize = 100 * 1024; // 100 KB
        savedata.dataBuf = calloc(1, dataSize);
        savedata.dataBufSize = dataSize;
        savedata.dataSize = dataSize;

        sceUtilitySavedataInitStart(&savedata);

        std::string loadedData;

        bool loading = true;

        while (loading)
        {
            switch(sceUtilitySavedataGetStatus())
            {
            case PSP_UTILITY_DIALOG_INIT:
                break;

            case PSP_UTILITY_DIALOG_VISIBLE:
                sceUtilitySavedataUpdate(1);
                break;

            case PSP_UTILITY_DIALOG_QUIT:
                sceUtilitySavedataShutdownStart();
                break;

            case PSP_UTILITY_DIALOG_FINISHED:
                break;

            case PSP_UTILITY_DIALOG_NONE:
                loadedData = std::string((char*)savedata.dataBuf);
                loading = false;
                break;
            }

            sceDisplayWaitVblankStart();
        }

        return loadedData;
    }
}
